### ISSUE TITLE
Привет, готов помочь

### ISSUE THREAD

**Issue by seldish-og** [cheatsnake/backend-cheats#1]
Могу написать как создать различные бд в докере и правильно к ним подключаться. Сам много шишек на этом набил будет кому-то полезно мб
1) PostgreSQL, MySQL 
2) Redis, Cassandra

**Comment by cheatsnake** [comment]
> Могу написать как создать различные бд в докере и правильно к ним подключаться. Сам много шишек на этом набил будет кому-то полезно мб
> 
> 1. PostgreSQL, MySQL
> 2. Redis, Cassandra

Привет! Спасибо за твой отклик.

Тема Докера сейчас действительно очень важная и востребованная для серверной разработки. Поэтому будет не лишним уделить ему больше внимания. Думаю твое предложение будет очень полезным. Я тоже пришел к подобной идее пару дней назад, поэтому создал отдельный репозиторий куда планирую добавлять различные примеры приложений, упакованных в Docker, на разных языках, с разными фреймворками и базами данных - https://github.com/cheatsnake/docker-recipes. Я буду рад любой помощи, можно контрибьютить в этот репозиторий или создать свой собственный.

**Comment by seldish-og** [comment]
Попробую через несколько дней 



Sent from Mail.ru app for iOS


Wednesday, 16 November 2022, 14:18 +0300 from ***@***.***  ***@***.***>:
