### ISSUE TITLE
add ORM to DB topic

### ISSUE THREAD

**Issue by sashagra** [cheatsnake/backend-cheats#12]

**Comment by cheatsnake** [comment]
> _No description provided._

Добавил упоминание об ORM в [топик про реляционные БД](https://github.com/cheatsnake/backend-cheats#%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F-%D0%B1%D0%B0%D0%B7%D0%B0-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85).
