### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [cheatsnake/backend-cheats#15]
Hello, I found some broken hyperlinks:
- [ ] https://github.com/cheatsnake/backend-cheats/blob/master/README_ENG.md#osi-network-model (file: README.md, status code: 404)
- [ ] https://youtube.com/playlistlist=PLBlnK6fEyqRiVhbXDGLXDk_OQAeuVcp2O (file: README.md, status code: 404)
- [ ] https://leesei.github.io/shell-network/ (file: README.md, status code: 404)
- [ ] https://betterprogramming.pub/developing-inside-a-container-5830e6882627 (file: README.md, status code: 410)

---

- [ ] https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Cookie (file: README_RUS.md, status code: 404)
- [ ] https://losst.pro/chem-arhitektura-arm-otlichaetsya-ot-x86 (file: README_RUS.md, status code: 404)
- [ ] %5B%3Chttps://en.wikipedia.org/wiki/Backdoor_(computing)%3E%5D(https://ru.wikipedia.org/wiki/%D0%91%D1%8D%D0%BA%D0%B4%D0%BE%D1%80) (file: README_RUS.md, status code: 404)
- [ ] https://hacker-basement.ru/2021/04/24/logi-linux-jurnalirovanie/ (file: README_RUS.md, error: DEPTH_ZERO_SELF_SIGNED_CERT)
- [ ] https://blog.askmentor.io/8-data-structure-everybody-should-know/ (file: README_RUS.md, error: EPROTO)
- [ ] https://ru.algorithmica.org/ru (file: README_RUS.md, status code: 404)
- [ ] https://ftp.zhirov.website/books/IT/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%8B/%D0%A1%D0%BF%D0%BE%D1%80%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B5%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%28%D0%A1%D1%82%D0%B8%D0%B2%D0%B5%D0%BD%20%D0%A5%D0%B0%D0%BB%D0%B8%D0%BC%2C%20%D0%A4%D0%B5%D0%BB%D0%B8%D0%BA%D1%81%20%D0%A5%D0%B0%D0%BB%D0%B8%D0%BC%29.pdf (file: README_RUS.md, error: ENOTFOUND)
- [ ] https://nodejsdev.ru/doc/ (file: README_RUS.md, status code: 404)
- [ ] https://insomnia.w3ref.ru/insomnia/get-started/ (file: README_RUS.md, error: ENOTFOUND)
- [ ] https://eternalhost.net/blog/sozdanie-saytov/chto-takoe-nginx? (file: README_RUS.md, error: EHOSTUNREACH)
- [ ] https://eternalhost.net/blog/hosting/web-server-apache (file: README_RUS.md, error: EHOSTUNREACH)

**Comment by cheatsnake** [comment]
@ndsvw Thank you very much for your consideration. Your issue gave me the idea to create a bot for automatically parsing all links and checking them for availability. For now, I will add this task to TODO list and when I have time I will do it.
