### ISSUE TITLE
Ошибка в картинке про Лигические операции

### ISSUE THREAD

**Issue by impocode** [cheatsnake/backend-cheats#3]
Привет!

В теме про [Лигические операции](https://github.com/cheatsnake/backend-cheats#логические-операции) картинка с примером для "ИЛИ" немного неправильная. В колонке "b" строкt 3 должна быть 1, а не 0.

**Comment by cheatsnake** [comment]
> Привет!
> 
> В теме про [Лигические операции](https://github.com/cheatsnake/backend-cheats#%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8) картинка с примером для "ИЛИ" немного неправильная. В колонке "b" строкt 3 должна быть 1, а не 0.

Спасибо, поправил.
